# Generated by Django 4.1.3 on 2022-12-18 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_tweet_options_alter_tweet_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follows",
            name="followers",
            field=models.ManyToManyField(
                default=0, related_name="following", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="follows",
            name="following",
            field=models.ManyToManyField(
                default=0, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
