# Generated by Django 4.1.3 on 2022-12-18 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_remove_follows_following_alter_follows_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="follows",
            name="following",
            field=models.ManyToManyField(
                default=0, related_name="isfollowing", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
