# Generated by Django 4.1.3 on 2022-12-19 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_alter_follows_followers_alter_follows_following_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="likers",
            field=models.ManyToManyField(
                default=None, related_name="likers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="likes",
        ),
        migrations.AddField(
            model_name="tweet",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
