# Generated by Django 4.1.3 on 2022-11-24 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="listings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("item", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("duration", models.TimeField()),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
