# Generated by Django 4.1.3 on 2022-12-10 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listings_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="Seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="Winner",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
