# Generated by Django 4.1.3 on 2022-11-24 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="desired",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wants",
                to="auctions.listings",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bids",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bids",
            name="bid_time",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listings",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listings",
            name="duration",
            field=models.DurationField(),
        ),
    ]
