# Generated by Django 4.1.3 on 2022-11-25 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_bids_id_alter_comments_id_alter_listings_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="onitem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.bids",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bids",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bids",
            name="desired",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auctions.listings"
            ),
        ),
        migrations.AlterField(
            model_name="listings",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
