# Generated by Django 4.1.3 on 2022-11-25 01:27

import datetime
from django.db import migrations, models
from django import utils

class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0009_comments_onitem_alter_bids_bidder_alter_bids_desired_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="date",
            field=models.DateField(
                verbose_name=utils.timezone.now
            ),
        ),
    ]
