# Generated by Django 4.1.3 on 2022-11-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_alter_bids_bid_time_alter_comments_comment_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bid_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="listings",
            name="date",
            field=models.DateField(),
        ),
    ]
