# Generated by Django 4.1.3 on 2022-11-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_alter_bids_bid_time_alter_comments_comment_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bids",
            name="bid_time",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="comment_time",
        ),
        migrations.RemoveField(
            model_name="listings",
            name="date",
        ),
    ]
