# Generated by Django 4.1.3 on 2022-11-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_remove_bids_bid_time_remove_comments_comment_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listings",
            old_name="item",
            new_name="Title",
        ),
        migrations.AddField(
            model_name="listings",
            name="Category",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listings",
            name="Description",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listings",
            name="Image",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listings",
            name="Starting_bid",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
