# Generated by Django 4.1.3 on 2022-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_bids_amount_alter_listings_starting_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="Active",
            field=models.BooleanField(default=True),
        ),
    ]
