# Generated by Django 4.1.3 on 2022-11-24 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listings"),
    ]

    operations = [
        migrations.CreateModel(
            name="bids",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.CharField(max_length=10)),
                ("bid_time", models.TimeField()),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Bidder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
