# Generated by Django 4.1.3 on 2022-12-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listings_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="Winner",
            field=models.IntegerField(default=0),
        ),
    ]
